-- SERA 지표 테이블 (조회수 / 주문수 / 클릭가치)
-- SERA xlsx 수동 업로드 데이터를 저장. 상품코드(P코드)가 매칭 키.
-- 재고 연동 현황 테이블에서 조회수·주문·클릭가치 컬럼으로 표시됨.

create table if not exists public.sera (
  id          bigint generated by default as identity primary key,
  code        text,                       -- 상품코드 (P0000OBD) ← 매칭 키
  name        text,                       -- 상품명 (prefix "[...]" 포함될 수 있음)
  views       integer default 0,          -- 조회수
  orders      integer default 0,          -- 주문수
  opv         numeric default 0,          -- 주문율 = 주문수 / 조회수
  click_value numeric default 0,          -- 클릭가치 = ESpV (가격 × 주문수 ÷ 조회수)
  updated_at  timestamptz default now()
);

create index if not exists sera_code_idx on public.sera (code);

-- anon 키로 읽기/쓰기 (전략·재고 테이블과 동일 정책)
alter table public.sera enable row level security;

drop policy if exists "sera_all" on public.sera;
create policy "sera_all" on public.sera
  for all using (true) with check (true);
